export default {
  '/index.html': 'Top',
  '/': 'Top',
  '/login': 'Login',
  '/create/account':'CreateAccount',
  '/create/account/predone': 'CreateAccountPreDone',
  '/create/account/done': 'CreateAccountDone',
  '/password/reset': 'PasswordReset',
  '/account': 'Account',
  '/question': 'Question',
  '/article/list': 'ArticleList',
  '/menu/list': 'MenuList',
  '/post/menu': 'PostMenu',
  '/post/article': 'PostArticle',
  '/article/item': 'ViewArticle',
  '/menu/item': 'ViewMenu',
  '/question/detail': 'QuestionDetail',
  '/post/question': 'PostQuestion',
  '/about': 'About'
}
